# Generated by Django 4.2.7 on 2023-11-15 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("PR", "Pinar del Río"),
                            ("AR", "Artemisa"),
                            ("LH", "La Habana"),
                            ("MA", "Mayabeque"),
                            ("MT", "Matanzas"),
                            ("CF", "Cienfuegos"),
                            ("VC", "Villa Clara"),
                            ("SS", "Sancti Spíritus"),
                            ("CA", "Ciego de Ávila"),
                            ("CM", "Camagüey"),
                            ("LT", "Las Tunas"),
                            ("HG", "Holguín"),
                            ("GR", "Granma"),
                            ("SC", "Santiago de Cuba"),
                            ("GT", "Guantánamo"),
                            ("IJ", "Isla de la Juventud"),
                        ],
                        max_length=2,
                        verbose_name="Provincia",
                    ),
                ),
                (
                    "port_type",
                    models.CharField(
                        choices=[
                            ("AP", "Aereopuerto"),
                            ("ET", "Estación de Tren"),
                            ("AL", "Almacén"),
                            ("PU", "Puerto"),
                        ],
                        max_length=2,
                        verbose_name="Tipo de puerto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": ["province"],
                "unique_together": {("province", "port_type")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commodity",
                    models.CharField(max_length=255, verbose_name="Mercancía"),
                ),
                ("value", models.IntegerField(verbose_name="Valor")),
                ("volume", models.IntegerField(default=0, verbose_name="Volumen")),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "required_delivery_date",
                    models.DateField(verbose_name="Fecha de entrega requerida"),
                ),
                (
                    "tax_percentage",
                    models.FloatField(default=0, verbose_name="Porcentaje de impuesto"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OH", "En espera"),
                            ("IP", "En proceso"),
                            ("PR", "Procesada"),
                        ],
                        default="OH",
                        max_length=2,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "ship_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_from",
                        to="core.location",
                        verbose_name="Lugar de origen",
                    ),
                ),
                (
                    "ship_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_to",
                        to="core.location",
                        verbose_name="Lugar de destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Órdenes",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "container_size",
                    models.IntegerField(verbose_name="Tamaño del Contenedor"),
                ),
                (
                    "carrier",
                    models.CharField(max_length=255, verbose_name="Transportista"),
                ),
                (
                    "travel_mode",
                    models.CharField(max_length=255, verbose_name="Modo de Viaje"),
                ),
                (
                    "fixed_freight_cost",
                    models.IntegerField(verbose_name="Costo Fijo de Flete"),
                ),
                (
                    "handling_cost",
                    models.IntegerField(
                        verbose_name="Costo de Manejo de Puerto/Aeropuerto/Estación de Tren"
                    ),
                ),
                (
                    "bunker_fuel_cost",
                    models.IntegerField(verbose_name="Costo de Bunker/Combustible"),
                ),
                (
                    "documentation_cost",
                    models.IntegerField(verbose_name="Costo de Documentación"),
                ),
                (
                    "equipment_cost",
                    models.IntegerField(verbose_name="Costo de Equipamiento"),
                ),
                ("extra_cost", models.IntegerField(verbose_name="Costo Extra")),
                (
                    "warehouse_cost",
                    models.IntegerField(default=0, verbose_name="Costo de Almacén"),
                ),
                ("transit_duty", models.FloatField(verbose_name="Derecho de Tránsito")),
                (
                    "custom_clearance_time",
                    models.IntegerField(verbose_name="Tiempo de Despacho Aduanero"),
                ),
                (
                    "handling_time",
                    models.IntegerField(
                        verbose_name="Tiempo de Manejo de Puerto/Aeropuerto/Estación de Tren"
                    ),
                ),
                ("extra_time", models.IntegerField(verbose_name="Tiempo Extra")),
                (
                    "transit_time",
                    models.IntegerField(verbose_name="Tiempo de Tránsito"),
                ),
                ("monday", models.BooleanField(default=True, verbose_name="Lunes")),
                ("tuesday", models.BooleanField(default=True, verbose_name="Martes")),
                (
                    "wednesday",
                    models.BooleanField(default=True, verbose_name="Miércoles"),
                ),
                ("thursday", models.BooleanField(default=True, verbose_name="Jueves")),
                ("friday", models.BooleanField(default=True, verbose_name="Viernes")),
                ("saturday", models.BooleanField(default=True, verbose_name="Sábado")),
                ("sunday", models.BooleanField(default=True, verbose_name="Domingo")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_routes",
                        to="core.location",
                        verbose_name="Lugar de destino",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_routes",
                        to="core.location",
                        verbose_name="Lugar de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta",
                "ordering": ["source"],
                "unique_together": {("source", "destination")},
            },
        ),
    ]
