# Generated by Django 4.2.7 on 2023-11-15 22:25

import apps.core.models.order
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="volume",
            field=models.IntegerField(
                default=0,
                validators=[apps.core.models.order.validate_max_value],
                verbose_name="Volumen",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="bunker_fuel_cost",
            field=models.IntegerField(
                default=0, verbose_name="Costo de Bunker/Combustible"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="documentation_cost",
            field=models.IntegerField(default=0, verbose_name="Costo de Documentación"),
        ),
        migrations.AlterField(
            model_name="route",
            name="equipment_cost",
            field=models.IntegerField(default=0, verbose_name="Costo de Equipamiento"),
        ),
        migrations.AlterField(
            model_name="route",
            name="fixed_freight_cost",
            field=models.IntegerField(default=0, verbose_name="Costo Fijo de Flete"),
        ),
        migrations.AlterField(
            model_name="route",
            name="handling_cost",
            field=models.IntegerField(
                default=0,
                verbose_name="Costo de Manejo de Puerto/Aeropuerto/Estación de Tren",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="transit_duty",
            field=models.FloatField(default=0, verbose_name="Derecho de Tránsito"),
        ),
    ]
