# Generated by Django 4.2.7 on 2023-11-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_order_volume_alter_route_bunker_fuel_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="travel_mode",
            field=models.CharField(
                choices=[
                    ("AI", "Aéreo"),
                    ("RA", "Ferrocarril"),
                    ("TR", "Camión"),
                    ("SE", "Marítimo"),
                ],
                max_length=2,
                verbose_name="Modo de Viaje",
            ),
        ),
    ]
