# Generated by Django 4.2.7 on 2023-11-16 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_route_travel_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Órden', 'verbose_name_plural': 'Órdenes'},
        ),
    ]
